-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  snapshot_date date NOT NULL,
  metric_name character varying NOT NULL,
  metric_value numeric DEFAULT 0,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_snapshots_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.favorites (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  restaurant_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT favorites_pkey PRIMARY KEY (id),
  CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT favorites_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.feature_flags (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid,
  key character varying NOT NULL,
  is_enabled boolean DEFAULT false,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT feature_flags_pkey PRIMARY KEY (id),
  CONSTRAINT feature_flags_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.menu_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  icon character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menu_categories_pkey PRIMARY KEY (id),
  CONSTRAINT menu_categories_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.menu_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  original_price numeric,
  category character varying NOT NULL,
  subcategory character varying,
  image_url character varying,
  tags ARRAY DEFAULT '{}'::text[],
  allergens ARRAY DEFAULT '{}'::text[],
  is_vegetarian boolean DEFAULT false,
  is_vegan boolean DEFAULT false,
  is_gluten_free boolean DEFAULT false,
  is_spicy boolean DEFAULT false,
  spicy_level integer DEFAULT 0 CHECK (spicy_level >= 0 AND spicy_level <= 5),
  calories integer,
  is_highlighted boolean DEFAULT false,
  is_new boolean DEFAULT false,
  is_available boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT menu_items_pkey PRIMARY KEY (id),
  CONSTRAINT menu_items_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['reservation_confirmed'::character varying, 'reservation_reminder'::character varying, 'reservation_cancelled'::character varying, 'review_request'::character varying, 'offer'::character varying, 'system'::character varying]::text[])),
  title character varying NOT NULL,
  message text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.offer_redemptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  offer_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reservation_id uuid,
  discount_applied numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offer_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT offer_redemptions_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id),
  CONSTRAINT offer_redemptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT offer_redemptions_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id)
);
CREATE TABLE public.offers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  discount_type character varying DEFAULT 'percentage'::character varying CHECK (discount_type::text = ANY (ARRAY['percentage'::character varying, 'fixed'::character varying, 'bogo'::character varying, 'special'::character varying, 'combo'::character varying]::text[])),
  discount_value character varying NOT NULL,
  promo_code character varying,
  valid_from date DEFAULT CURRENT_DATE,
  valid_until date NOT NULL,
  valid_days ARRAY DEFAULT '{monday,tuesday,wednesday,thursday,friday,saturday,sunday}'::text[],
  valid_hours_start time without time zone,
  valid_hours_end time without time zone,
  min_party_size integer,
  max_party_size integer,
  is_active boolean DEFAULT true,
  usage_count integer DEFAULT 0,
  max_usage integer,
  terms_conditions text,
  image_url character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offers_pkey PRIMARY KEY (id),
  CONSTRAINT offers_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.reservations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  table_id uuid,
  date date NOT NULL,
  time time without time zone NOT NULL,
  end_time time without time zone,
  guest_count integer NOT NULL CHECK (guest_count > 0),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'arrived'::character varying, 'seated'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'no_show'::character varying]::text[])),
  occasion character varying,
  special_request text,
  internal_notes text,
  deposit_amount numeric DEFAULT 0,
  deposit_paid boolean DEFAULT false,
  deposit_paid_at timestamp with time zone,
  qr_code character varying NOT NULL UNIQUE,
  confirmation_code character varying,
  source character varying DEFAULT 'web'::character varying CHECK (source::text = ANY (ARRAY['web'::character varying, 'app'::character varying, 'phone'::character varying, 'walk_in'::character varying, 'partner'::character varying]::text[])),
  arrived_at timestamp with time zone,
  seated_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  has_review boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  payment_intent_id character varying,
  CONSTRAINT reservations_pkey PRIMARY KEY (id),
  CONSTRAINT reservations_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT reservations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id)
);
CREATE TABLE public.restaurant_staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  staff_role character varying DEFAULT 'waiter'::character varying CHECK (staff_role::text = ANY (ARRAY['waiter'::character varying, 'host'::character varying, 'manager'::character varying, 'cashier'::character varying, 'chef'::character varying]::text[])),
  permissions jsonb DEFAULT '{"canCheckIn": true, "canEditMenu": false, "canViewMenu": true, "canViewReports": false, "canChangeTables": true, "canManageWaitlist": true, "canViewReservations": true}'::jsonb,
  is_active boolean DEFAULT true,
  hired_at date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_staff_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_staff_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT restaurant_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.restaurants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid,
  name character varying NOT NULL,
  description text,
  address character varying,
  phone character varying,
  email character varying,
  website character varying,
  instagram character varying,
  facebook character varying,
  cuisine_type character varying,
  zone character varying,
  price_range character varying DEFAULT '$$'::character varying CHECK (price_range::text = ANY (ARRAY['$'::character varying, '$$'::character varying, '$$$'::character varying, '$$$$'::character varying]::text[])),
  image_url character varying,
  photos ARRAY DEFAULT '{}'::text[],
  features ARRAY DEFAULT '{}'::text[],
  payment_methods ARRAY DEFAULT '{Efectivo,Tarjeta}'::text[],
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  open_time time without time zone DEFAULT '12:00:00'::time without time zone,
  close_time time without time zone DEFAULT '23:00:00'::time without time zone,
  opening_hours jsonb DEFAULT '{"friday": {"open": "12:00", "close": "00:00"}, "monday": {"open": "12:00", "close": "23:00"}, "sunday": {"open": "12:00", "close": "22:00"}, "tuesday": {"open": "12:00", "close": "23:00"}, "saturday": {"open": "12:00", "close": "00:00"}, "thursday": {"open": "12:00", "close": "23:00"}, "wednesday": {"open": "12:00", "close": "23:00"}}'::jsonb,
  settings jsonb DEFAULT '{"autoConfirm": false, "depositDays": ["friday", "saturday"], "allowWalkIns": true, "depositHours": ["20:00", "21:00"], "maxPartySize": 12, "depositAmount": 200, "noShowPenalty": 100, "reminderHours": [24, 2], "depositRequired": false, "minAdvanceHours": 2, "maxReservationDays": 30}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  has_deposit boolean DEFAULT false,
  image text,
  latitude numeric,
  longitude numeric,
  holidays jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT restaurants_pkey PRIMARY KEY (id),
  CONSTRAINT restaurants_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reservation_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  food_rating integer CHECK (food_rating >= 1 AND food_rating <= 5),
  service_rating integer CHECK (service_rating >= 1 AND service_rating <= 5),
  ambiance_rating integer CHECK (ambiance_rating >= 1 AND ambiance_rating <= 5),
  value_rating integer CHECK (value_rating >= 1 AND value_rating <= 5),
  comment text,
  photos ARRAY DEFAULT '{}'::text[],
  tags ARRAY DEFAULT '{}'::text[],
  is_verified boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  helpful_count integer DEFAULT 0,
  response text,
  responded_at timestamp with time zone,
  responded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT reviews_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id),
  CONSTRAINT reviews_responded_by_fkey FOREIGN KEY (responded_by) REFERENCES public.users(id)
);
CREATE TABLE public.system_metrics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid,
  event_type character varying NOT NULL,
  value numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT system_metrics_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.tables (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  number integer NOT NULL,
  name character varying,
  capacity integer NOT NULL CHECK (capacity > 0),
  min_capacity integer DEFAULT 1,
  status character varying DEFAULT 'available'::character varying CHECK (status::text = ANY (ARRAY['available'::character varying, 'occupied'::character varying, 'reserved'::character varying, 'blocked'::character varying, 'disabled'::character varying]::text[])),
  zone character varying DEFAULT 'main'::character varying,
  position_x integer DEFAULT 0,
  position_y integer DEFAULT 0,
  shape character varying DEFAULT 'round'::character varying CHECK (shape::text = ANY (ARRAY['round'::character varying, 'square'::character varying, 'rectangle'::character varying, 'oval'::character varying]::text[])),
  width integer DEFAULT 60,
  height integer DEFAULT 60,
  rotation integer DEFAULT 0,
  is_outdoor boolean DEFAULT false,
  is_vip boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT tables_pkey PRIMARY KEY (id),
  CONSTRAINT tables_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  phone character varying,
  password_hash character varying,
  avatar_url character varying,
  role character varying DEFAULT 'customer'::character varying CHECK (role::text = ANY (ARRAY['customer'::character varying, 'restaurant_admin'::character varying, 'staff'::character varying, 'super_admin'::character varying]::text[])),
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  verification_code character varying,
  reset_token character varying,
  reset_token_expires timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.verification_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  code character varying NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  attempts integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT verification_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.waitlist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  restaurant_id uuid NOT NULL,
  user_id uuid,
  name character varying NOT NULL,
  phone character varying NOT NULL,
  email character varying,
  party_size integer NOT NULL CHECK (party_size > 0),
  status character varying DEFAULT 'waiting'::character varying CHECK (status::text = ANY (ARRAY['waiting'::character varying, 'notified'::character varying, 'confirmed'::character varying, 'seated'::character varying, 'left'::character varying, 'cancelled'::character varying, 'no_show'::character varying]::text[])),
  estimated_wait integer DEFAULT 15,
  actual_wait integer,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['normal'::character varying, 'vip'::character varying, 'priority'::character varying]::text[])),
  preferred_zone character varying,
  notes text,
  position integer,
  notified_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  seated_at timestamp with time zone,
  table_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT waitlist_pkey PRIMARY KEY (id),
  CONSTRAINT waitlist_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id),
  CONSTRAINT waitlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT waitlist_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id)
);